# Build stage
FROM node:22 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Arguments for environment variables
ARG VITE_API_URL
ARG VITE_CLOUDINARY_CLOUD_NAME
ARG VITE_CLOUDINARY_UPLOAD_PRESET
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID

# Convert arguments to environment variables
ENV VITE_API_URL=$VITE_API_URL 
ENV VITE_CLOUDINARY_CLOUD_NAME=$VITE_CLOUDINARY_CLOUD_NAME 
ENV VITE_CLOUDINARY_UPLOAD_PRESET=$VITE_CLOUDINARY_UPLOAD_PRESET 
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY 
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN 
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID 
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET 
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID 
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID 
ENV VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID

RUN npm run build

# Production stage - Tối giản tối đa
FROM alpine:latest
WORKDIR /app

# Chỉ copy thư mục dist vào image, không cài đặt gì thêm
COPY --from=builder /app/dist ./dist

# Image này không chạy gì cả, nó chỉ đóng vai trò như file zip chở hàng
CMD ["echo", "Static files container - Please extract /app/dist"]