import {
  SuggestedVocabularyItem,
  SuggestionMemoryStatus,
  SuggestionReviewStat,
  SuggestionSchedulePoint,
} from "../../types/UserVocabularyProgressV2";

const now = Date.now();
const dayMs = 24 * 60 * 60 * 1000;

export const reviewStats: SuggestionReviewStat[] = [
  { label: "Đến hạn", value: 12, color: "#ef4444" },
  { label: "Sắp quên", value: 9, color: "#f59e0b" },
  { label: "Ôn sớm", value: 7, color: "#10b981" },
];

export const schedulePoints: SuggestionSchedulePoint[] = [
  { label: "Hôm nay", value: 42 },
  { label: "Ngày mai", value: 25 },
  { label: "Thứ 3", value: 18 },
  { label: "Thứ 4", value: 22 },
  { label: "Thứ 5", value: 20 },
  { label: "Thứ 6", value: 10 },
  { label: "Thứ 7", value: 5 },
];

export const memoryStatuses: SuggestionMemoryStatus[] = [
  { label: "Đã nắm vững", status: "mastered", value: 236, percent: 48, color: "#10b981" },
  { label: "Đang học", status: "reviewing", value: 206, percent: 42, color: "#2563eb" },
  { label: "Sắp quên", value: 38, percent: 8, color: "#ef4444" },
  { label: "Chưa ôn", value: 20, percent: 2, color: "#cbd5e1" },
];

export const suggestedVocabularies: SuggestedVocabularyItem[] = [
  {
    vocabularyId: "vocab_allocate",
    word: "allocate",
    phonetic: "/ˈæləkeɪt/",
    meaning: "phân bổ, phân phối",
    topic: "Business",
    topicColor: "#dbeafe",
    level: "B2",
    priority: "Cao",
    pRecall: 0.15,
    pRecallPercent: 15,
    dueLabel: "Hôm nay",
    dueTone: "danger",
    memory: {
      difficulty: 13,
      half_life_days: 1.2,
      due_at: new Date(now).toISOString(),
      status: "reviewing",
      last_p_recall: 0.15,
      last_interval_days: 1,
      last_seen_count: 4,
      last_hard_count: 2,
      last_medium_count: 1,
      last_easy_count: 1,
      last_skip_count: 0,
      last_learning_effort: 9.2,
      last_recall_failure_score: 7,
      last_dhp_recall_result: "forgot",
    },
  },
  {
    vocabularyId: "vocab_perspective",
    word: "perspective",
    phonetic: "/pərˈspektɪv/",
    meaning: "góc nhìn, quan điểm",
    topic: "Business",
    topicColor: "#dbeafe",
    level: "B2",
    priority: "Trung bình",
    pRecall: 0.32,
    pRecallPercent: 32,
    dueLabel: "Ngày mai",
    dueTone: "warning",
    memory: {
      difficulty: 10,
      half_life_days: 3.8,
      due_at: new Date(now + dayMs).toISOString(),
      status: "reviewing",
      last_p_recall: 0.32,
      last_interval_days: 2,
      last_seen_count: 3,
      last_hard_count: 1,
      last_medium_count: 2,
      last_easy_count: 0,
      last_skip_count: 0,
      last_learning_effort: 6.5,
      last_recall_failure_score: 4.5,
      last_dhp_recall_result: "remembered",
    },
  },
  {
    vocabularyId: "vocab_contemporary",
    word: "contemporary",
    phonetic: "/kənˈtempəreri/",
    meaning: "đương thời, hiện đại",
    topic: "Culture",
    topicColor: "#dcfce7",
    level: "B2",
    priority: "Trung bình",
    pRecall: 0.45,
    pRecallPercent: 45,
    dueLabel: "2 ngày tới",
    dueTone: "warning",
    memory: {
      difficulty: 9,
      half_life_days: 5,
      due_at: new Date(now + dayMs * 2).toISOString(),
      status: "reviewing",
      last_p_recall: 0.45,
      last_interval_days: 2,
    },
  },
  {
    vocabularyId: "vocab_implement",
    word: "implement",
    phonetic: "/ˈɪmplɪment/",
    meaning: "thực thi, triển khai",
    topic: "Work",
    topicColor: "#dcfce7",
    level: "B1",
    priority: "Cao",
    pRecall: 0.18,
    pRecallPercent: 18,
    dueLabel: "3 ngày tới",
    dueTone: "danger",
    memory: {
      difficulty: 12,
      half_life_days: 1.8,
      due_at: new Date(now + dayMs * 3).toISOString(),
      status: "reviewing",
      last_p_recall: 0.18,
      last_interval_days: 3,
    },
  },
  {
    vocabularyId: "vocab_viable",
    word: "viable",
    phonetic: "/ˈvaɪəbl/",
    meaning: "khả thi, có thể thực hiện",
    topic: "Economics",
    topicColor: "#ede9fe",
    level: "B1",
    priority: "Thấp",
    pRecall: 0.72,
    pRecallPercent: 72,
    dueLabel: "5 ngày tới",
    dueTone: "success",
    memory: {
      difficulty: 6,
      half_life_days: 18,
      due_at: new Date(now + dayMs * 5).toISOString(),
      status: "reviewing",
      last_p_recall: 0.72,
      last_interval_days: 5,
    },
  },
  {
    vocabularyId: "vocab_incentive",
    word: "incentive",
    phonetic: "/ɪnˈsentɪv/",
    meaning: "động lực, sự khuyến khích",
    topic: "Business",
    topicColor: "#dbeafe",
    level: "B2",
    priority: "Thấp",
    pRecall: 0.85,
    pRecallPercent: 85,
    dueLabel: "7 ngày tới",
    dueTone: "success",
    memory: {
      difficulty: 5,
      half_life_days: 36,
      due_at: new Date(now + dayMs * 7).toISOString(),
      status: "reviewing",
      last_p_recall: 0.85,
      last_interval_days: 7,
    },
  },
  {
    vocabularyId: "vocab_strategy",
    word: "strategy",
    phonetic: "/ˈstrætədʒi/",
    meaning: "chiến lược",
    topic: "Business",
    topicColor: "#dbeafe",
    level: "B2",
    priority: "Trung bình",
    pRecall: 0.55,
    pRecallPercent: 55,
    dueLabel: "10 ngày tới",
    dueTone: "warning",
    memory: {
      difficulty: 8,
      half_life_days: 8,
      due_at: new Date(now + dayMs * 10).toISOString(),
      status: "reviewing",
      last_p_recall: 0.55,
      last_interval_days: 10,
    },
  },
];
